import Head from 'next/head'
import Image from 'next/image'

import Links from "./../components/Links"
const Home = () => {
  return (
    <div className="main-page">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Welcome Page
      <Links/>
      
    </div>
  )
}
export default Home